PRESIDENT = 'PR'
VICEPRESIDENT = 'VP'
TREASURER = 'TR'
SECRETARY = 'SE'
VOCAL = 'VO'
MEMBER = 'ME'
POSITION_OPTIONS = (
    (PRESIDENT, 'President'),
    (VICEPRESIDENT, 'Vice-President'),
    (TREASURER, 'Treasurer'),
    (SECRETARY, 'Secretary'),
    (VOCAL, 'Vocal'),
    (MEMBER, 'Member'),
)
MALE = 'M'
FEMALE = 'F'
GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female')
)
BASIC_SPANISH_I = 'ESPA-3101'
BASIC_SPANISH_II = 'ESPA-3102'
TECHNICAL_REPORT_WRITING_SPANISH = 'ESCO-4005'
BASIC_ENGLISH_I = 'INGL-3101'
BASIC_ENGLISH_II = 'INGL-3102'
TECHNICAL_REPORT_WRITING_ENGLISH = 'INCO-4025'
PRE_CALCULUS_I = 'MATE-3171'
PRE_CALCULUS_II = 'MATE-3172'
DISCRETE_MATHEMATICS = 'MATE-3175'
CALCULUS_I = 'MATE-3031'
CALCULUS_II = 'MATE-3032'
STATISTICS_USING_COMPUTERS = 'MATE-3026'
ALGORITHMS_AND_PROGRAM_DEVELOPMENT_I = 'COTI-3101'
ALGORITHMS_AND_PROGRAM_DEVELOPMENT_II = 'COTI-3102'
DATA_STRUCTURES = 'SICI-4036'
WEB_APPLICATIONS = 'COTI-4210'
DATABASE = 'SICI-4030'
COURSES_CHOICES = (
    (ALGORITHMS_AND_PROGRAM_DEVELOPMENT_I, 'Algorithms and Program Development I'),
    (ALGORITHMS_AND_PROGRAM_DEVELOPMENT_II, 'Algorithms and Program Development II'),
    (DATA_STRUCTURES, 'Data Structures'),
    (WEB_APPLICATIONS, 'Web Applications'),
    (DATABASE, 'Database'),
    (PRE_CALCULUS_I, 'Pre-Calculus I'),
    (PRE_CALCULUS_II, 'Pre-Calculus II'),
    (DISCRETE_MATHEMATICS, 'Discrete Mathematics'),
    (CALCULUS_I, 'Calculus I'),
    (CALCULUS_II, 'Calculus II'),
    (STATISTICS_USING_COMPUTERS, 'Statistics Using Computers'),
    (BASIC_SPANISH_I, 'Basic Spanish I'),
    (BASIC_SPANISH_II, 'Basic Spanish II'),
    (TECHNICAL_REPORT_WRITING_SPANISH, 'Technical Report Writing In Spanish'),
    (BASIC_ENGLISH_I, 'Basic English I'),
    (BASIC_ENGLISH_II, 'Basic English II'),
    (TECHNICAL_REPORT_WRITING_ENGLISH, 'Technical Report Writing In English'),
)